### ISSUE TITLE
Expo font loading isssue

### ISSUE THREAD

**Issue by KenilDomadia** [jbosse/ignite-expo-boilerplate#2]
I just installed the ignite boilerplate and did npm start and found the issue saying `fontFamily 'Avenir-Book' is not a system font and has not been loaded through Expo.Font.loadAsync` and the font doesn't show up in the launch screen. Maybe, we need to load the font before the app is loaded using Expo.Font.loadAsync

**Comment by jbosse** [comment]
I just tried running on the Android simulator and received the same error. I cannot get a default boilerplate install running on Android. I was having trouble getting the Android emulator running on my machine when I first started learning react due to an incompatibility with the new Apple file system. Avenir is a default font on iOS and I can't figure how Infinite Red is loading onto Android so I don't know how to fix it yet. 

In the meantime the workaround would be to find and replace `Avenir-Book` and `Avenir-Black` with a default Android font. Is Roboto default?

**Comment by JadRizk** [comment]
Okay, i found a solution, for now, that is work fine. Instead of setting up the default font for Android, we can set the font according to the platform at hand. 

In this boilerplate the font is defined in 2 places: "./Themes/Font.js" and in "./ignite/DevScreens/DevTheme/Font.js".

Start by importing Platform:
`import { Platform } from 'react-native'`

Then replace 'type' with the following code:
`const type = {
  base: (Platform.OS === 'ios' ? 'Helvetica Neue' : 'sans-serif'),
  bold: (Platform.OS === 'ios' ? 'HelveticaNeue-Bold' : 'sans-serif-condensed'),
  emphasis: (Platform.OS === 'ios' ? 'HelveticaNeue-Italic' : 'sans-serif')
}`

The fonts used here are the default fonts for IOS and Android. (I couldn't find an italic font for Android system)
Hope it helped.

**Comment by JadRizk** [comment]
Okay, i found a solution, for now, that is work fine. Instead of setting up the default font for Android, we can set the font according to the platform at hand.

In this boilerplate the font is defined in 2 places: "./Themes/Font.js" and in "./ignite/DevScreens/DevTheme/Font.js".

Start by importing Platform:
import { Platform } from 'react-native'

Then replace 'type' with the following code:
`const type = {
  base: (Platform.OS === 'ios' ? 'Helvetica Neue' : 'sans-serif'),
  bold: (Platform.OS === 'ios' ? 'HelveticaNeue-Bold' : 'sans-serif-condensed'),
  emphasis: (Platform.OS === 'ios' ? 'HelveticaNeue-Italic' : 'sans-serif')
}`

The fonts used here are the default fonts for IOS and Android. (I couldn't find an italic font for Android system)
Hope it helped.

**Comment by jbosse** [comment]
@KenilDomadia I have incorporated the solution from @JadRizk and it seems to be working. I have updated the packages on NPM.
 Can you verify that it works you as well?

**Comment by jbosse** [comment]
Actually in playing with it I noticed that my hack for trying to get italic for emphasis is wrong on android. I will have to fix that.
